### ISSUE TITLE
Problems with analysis Tools

### ISSUE THREAD

**Issue by leonmti** [julie-forman-kay-lab/IDPConformerGenerator#281]
Hi I am fairly new to IDPConformer Generator, I wanted to explore the analysis tools, but I have troubles finding the tools for radius of gyration, end-to-end distances, asphericity, and Cα−Cα distance and distance-difference matrices. Am I missing something, or do I need to use additional software?

**Comment by menoliu** [comment]
Hi @leonmti! Thank you for your interest in our IDP/IDR ensemble generator. Although we cannot calculate Rg, Ree, A, and Ca-Ca distances within IDPConformerGenerator currently, we do have plans to add these simple calculators for quickly categorise ensembles later.

If you're interested in a back-calculator suite for ensembles (i.e. to obtain back-calculated experimental data), please refer to SPyCi-PDB (https://github.com/julie-forman-kay-lab/SPyCi-PDB).

If you're wondering what IDPConformerGenerator and SPyCi-PDB do, please refer to the documentation we have written here:

https://idpconformergenerator.readthedocs.io/en/latest/
https://spyci-pdb.readthedocs.io/en/stable/

Hope this helps,
Nemo

**Comment by formankay** [comment]
Hi Nemo, there are tools/scripts for calculating Rg, Ree, A and Ca-Ca distances that we published in the original IDPConfGen paper. How can those be accessed?
Thanks,
Julie
________________________________

**Comment by menoliu** [comment]
Thank you for the reminder Julie.

@leonmti I have attached the diversity analysis script here. They are part of all of the scripts we used for the IDPConformerGenerator J Phys Chem A paper, and can be found in the supplemental archive. Please change the file extension to `.py` instead of the attached `.txt`.

[Calculate_Diversity.txt](https://github.com/user-attachments/files/15891427/Calculate_Diversity.txt)
