### ISSUE TITLE
[DOCS] DSSP installation and server

### ISSUE THREAD

**Issue by joaomcteixeira** [julie-forman-kay-lab/IDPConformerGenerator#48]
Dear All,

The HSSP and DSSP repository (previously XSSP) has recently been split into HSSP and DSSP separate repositories - https://github.com/cmbi/hssp/issues/122.

Here are the links:
* HSSP: https://github.com/cmbi/hssp
* DSSP: https://github.com/cmbi/dssp

Our `ssext` uses the DSSP one.

**Comment by joaomcteixeira** [comment]
Hi @marbesu-instadeep 
Thanks for your contribution. It's very welcomed.
Cheers!

**Comment by menoliu** [comment]
As of Ubuntu 24.04LTS, this is a standalone alternative since there may be `libboost` versioning issues. Please see the resource [here](https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/dssp_3.0.0-3build1_amd64.deb.html) to see the latest version (DSSP v3) from Ubuntu's 20.04 LTS packages.

You may have to `wget` the binary package links and `sudo dpkg -i ***.deb` to install the requirements first before installing the `dssp.deb`. Please also make sure if your system is ARM64 or AMD64.
